In [19]:
import numpy as np
np.sum(2 ** np.random.random_integers(0, 6, [4, 100]),0)

array([132, 128, 114,  12,  72,  71,  88,  20,  98, 100,  32,  52, 168,
        23, 116, 162,  82, 114, 116,  84,  46, 176, 105, 130,  54,  88,
        21, 168,  82,  25,  99, 145,  51, 176, 116,  75,  36,  81,  57,
        97,  19, 116, 176,  25,  25,  52, 106,  36,  80,  30, 146,  84,
        83,  42,  18, 104, 100, 116, 146,  71, 130,  82,  24,  44,  67,
        23,  73,  64,  40,  92,  25,  12, 132,  57, 138,  86,  26, 193,
        15,  42,  30, 146,  77,  38, 108,  71, 168,  34,  99,  89, 128,
        36,  13,  88,  75,  54, 114,  96, 112,  98], dtype=int32)

In [163]:
a = np.cumsum(2 ** np.random.random_integers(0, 6, [100, 7]),1)

In [169]:
b = np.argmax(a>=21,1)
c = np.any(a>=21,1)

In [171]:
a = np.multiply(np.diag(a[:,b]),c)


In [71]:
np.mean(np.diag(a[:,b])-21)

In [81]:
test = np.arange(1,13,1)
test = test.reshape([4,3])
test

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [99]:
a = test>5
b = np.argmax(a,0)
b

array([2, 2, 1], dtype=int64)

In [130]:
temp = np.array([0,1,2,3])
np.diag(test[b,:])

array([7, 8, 6])

In [162]:
np.nanmean(1)

1.0

In [191]:
test = np.int8(np.random.random_integers(1,4,10))
test.itemsize*test.size

10

In [182]:
np.nanmean(test)

2.334

In [208]:
d1 = np.std(np.array([1,2,3]),ddof= 0)
d2 = np.std(np.array([4,5,6]),ddof = 0)
d3 = np.std(np.array([1,2,3,4,5,6]),ddof = 0)
np.corrcoef(np.array([1,2,3]),np.array([4,5,6]))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [209]:
print(d1,d2,d1+d2,d3)

0.816496580928 0.816496580928 1.63299316186 1.70782512766
