In [2]:
import numpy as np

In [163]:
a = np.cumsum(2 ** np.random.random_integers(0, 6, [100, 7]),1)

In [169]:
b = np.argmax(a>=21,1)
c = np.any(a>=21,1)

In [171]:
a = np.multiply(np.diag(a[:,b]),c)


In [71]:
np.mean(np.diag(a[:,b])-21)

In [81]:
test = np.arange(1,13,1)
test = test.reshape([4,3])
test

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [99]:
a = test>5
b = np.argmax(a,0)
b

array([2, 2, 1], dtype=int64)

In [130]:
temp = np.array([0,1,2,3])
np.diag(test[b,:])

array([7, 8, 6])

In [162]:
np.nanmean(1)

1.0

In [191]:
test = np.int8(np.random.random_integers(1,4,10))
test.itemsize*

10

In [182]:
np.nanmean(test)

2.334

In [208]:
d1 = np.std(np.array([1,2,3]),ddof= 0)
d2 = np.std(np.array([4,5,6]),ddof = 0)
d3 = np.std(np.array([1,2,3,4,5,6]),ddof = 0)
np.corrcoef(np.array([1,2,3]),np.array([4,5,6]))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [209]:
print(d1,d2,d1+d2,d3)

0.816496580928 0.816496580928 1.63299316186 1.70782512766


In [41]:
test = np.random.random_integers(0, 6, [5, 1])
test

array([[1],
       [4],
       [4],
       [5],
       [3]])

In [59]:
cond = np.nonzero(test==4)
test_new =  np.delete(test, cond[0])

In [60]:
test_new

array([1, 5, 3])

In [58]:
np.squeeze(cond)

array([[1, 2],
       [0, 0]], dtype=int64)

In [61]:
2**8

256

In [7]:
%%timeit
test = np.int16(np.random.random_integers(0, 6, [10**8, 1]))
#test.itemsize*test.size/1024/1024

1 loops, best of 3: 1.31 s per loop


In [36]:
a = np.int8(np.random.random_integers(0, 6, [10**8, 1]))

a = np.concatenate((a, np.int8(np.random.random_integers(0, 6, [10**8, 1]))), axis =0)

In [22]:
a.size*a.itemsize/1024/1024/2

95.367431640625

In [28]:
%precision 20

'%.20f'

In [29]:
np.mean(a)


3.00011296500000002041

In [37]:
np.mean(a)

3.00038715499999986136